server:
  port: ${PORT:8080}
  error:
    include-stacktrace: NEVER
    include-binding-errors: NEVER

spring:
  application:
    name: gestao-rh
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestaorh-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    tomcat:
      max-active: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql